import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import script from 'next/script' // under stading the script component
import Link from 'next/link' // link componet use to link pages 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hytech Developer</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <ul>
          <li><Link href="/"><a>Home</a></Link></li>
          <li><Link href="/about"><a>About</a></Link></li>
          <li><Link href="/blogs"><a>Blogs</a></Link></li>
          <li><Link href="/services"><a>Services</a></Link></li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
        <span className="myspan">Hytech Developer</span>
        </h1>

        <p className={styles.description}>
         Blog by Developers for the Developers.
        </p>
          <div className="bogs">
            <div className="blogItems">
              
              <h1>How to start Coding</h1>
              <p>Pick any language to understand fundamental of the programminga language</p>
            </div>
          </div>
       
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
