import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import script from 'next/script' // under stading the script component
// link componet use to link pages 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hytech Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container} style={{ textAlign: 'center' }}>
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="myspan">Hytech Developer</span>
        </h1>
        <p className={styles.description}>
          Blog by Developers for the Developers.
        </p>
            <Image src='/home.avif' width="800" height="600" />
       

      </main>


    </div>
  )
}
